### ISSUE TITLE
Eror 404 on IHaskell installation guide link from http://www.datahaskell.org/docs/

### ISSUE THREAD

**Issue by wizzup** [DataHaskell/docs#16]
http://www.datahaskell.org/docs/tutorial/ihaskell-installation.html

**Comment by NickSeagull** [comment]
Hello, thanks for submitting this issue 😄 
How did you get to that link? I can't find a page that links to it.

**Comment by mdibaiee** [comment]
@NickSeagull the main page of documentation [datahaskell.org/docs](http://www.datahaskell.org/docs) links to it, third paragraph. :grin:

**Comment by NickSeagull** [comment]
oh

**Comment by NickSeagull** [comment]
Fixed
