### ISSUE TITLE
Markdown not rendering correctly

### ISSUE THREAD

**Issue by mdibaiee** [DataHaskell/docs#8]
It seems there is a problem with the markdown engine.

Everything's fine on my local machine:
![local](https://pageshot.net/images/31bb9c5b-f4a6-4e44-8b82-f58aa42facfa)

But this is how the markdown is rendered at datahaskell.org/docs:
![online](https://pageshot.net/images/bbcabd39-6e76-4eb2-9f9d-664edd5ea66f)

According to [this page](https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/) we're using `kramdown` which should just work fine.

**Comment by mdibaiee** [comment]
@DataHaskell/everyone anyone with prior experience of using Jekyll has any idea why this happens? I searched but couldn't find anything.

**Comment by Drezil** [comment]
markdown (instead of github-markdown) needs empty lines between distinct things..

I think adding empty lines before sourcecode and before enumerations (like \* after notes) could fix things

**Comment by NickSeagull** [comment]
Yep, thats true @mdibaiee, I didnt think about it! 👍

**Comment by mdibaiee** [comment]
@Drezil but why does it work on my machine? It's kind of weird, my only guess would be the problem of `\r\n` and alike, but I'm on Linux and GitHub's servers are Linux, too (or are they?).

But it's worth a try!

**Comment by mdibaiee** [comment]
@Drezil Yep, it seems you are right, the problem is solved after putting a new line between blocks. Thank you!
